CREATE TABLE burgers (
	id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	burger_name VARCHAR(255),
	devoured BOOLEAN DEFAULT FALSE
);

CREATE TABLE customers (
	id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	customer_name VARCHAR(255),
	burgerId INT,
	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
